# Add `~/bin` to the `$PATH`
export PATH="$HOME/bin:$PATH";

DOTFILES=$HOME/.dotfiles

# source file
source_if_exists () {
    if test -r "$1"; then
        source "$1"
    fi
}

# source from folder
source_files(){
  local folder=$1
  find "$DOTFILES" -type f -o -type l | while IFS= read -r file; do
    source_if_exists "$file"
  done
}

#temporal, back up of zshrc after installations
cp $HOME/.zshrc $HOME/code/zshrc.backup


# Load the dotfiles
source_files $DOTFILES

# oh my zsh configuration
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git)
source $ZSH/oh-my-zsh.sh

# node configuration
export NVM_DIR="$HOME/.nvm"
[ -s "$HOMEBREW_PREFIX/opt/nvm/nvm.sh" ] && \. "$HOMEBREW_PREFIX/opt/nvm/nvm.sh" # This loads nvm
[ -s "$HOMEBREW_PREFIX/opt/nvm/etc/bash_completion.d/nvm" ] && \. "$HOMEBREW_PREFIX/opt/nvm/etc/bash_completion.d/nvm" # This loads nvm bash_completion
export PATH="/opt/homebrew/opt/node@20/bin:$PATH"
export LDFLAGS="-L/opt/homebrew/opt/node@20/lib"
export CPPFLAGS="-I/opt/homebrew/opt/node@20/include"
